set client_encoding=UTF8;

/*languages*/
create table F1010
(		LSID VARCHAR(16) NOT NULL,
		LSNAME VARCHAR(128) NOT NULL,
		LSLOC VARCHAR(1024) NOT NULL,
		LSSORT INT NOT NULL,
		PRIMARY KEY (LSID)
);

/*users*/
create table F0301
(		USID VARCHAR(32) NOT NULL,
		USPSWD VARCHAR(32) NOT NULL,
		USNAME VARCHAR(32) NOT NULL,
		USST SMALLINT NOT NULL,
		USLSID VARCHAR(16) NOT NULL,
		USPN SMALLINT NOT NULL,
		/*reading style*/
		PRIMARY KEY (USID),
		FOREIGN KEY (USLSID) REFERENCES F1010 (LSID)
);

/*user-creations*/
create table F0309
(		UCID SERIAL NOT NULL,
		UCCRDD VARCHAR(10) NOT NULL,
		UCCRDT VARCHAR(8) NOT NULL,
		UCUSID VARCHAR(32) NOT NULL,
		UCPV VARCHAR(6) NOT NULL,
		UCMV VARCHAR(6) NOT NULL,
		UCST SMALLINT NOT NULL,
		PRIMARY KEY (UCID)
);

/*roles*/
create table F0310
(		RLID VARCHAR(32) NOT NULL,
		RLNAME VARCHAR(32) NOT NULL,
		PRIMARY KEY (RLID)
);

/*user-roles*/
create table F0311
(		URID SERIAL NOT NULL,
		URUSID VARCHAR(32) NOT NULL,
		URRLID VARCHAR(32) NOT NULL,
		PRIMARY KEY (URID),
		UNIQUE (URUSID,URRLID),
		FOREIGN KEY (URUSID) REFERENCES F0301 (USID),
		FOREIGN KEY (URRLID) REFERENCES F0310 (RLID)
);

/*authorities*/
create table F0320
(		AUID VARCHAR(16) NOT NULL,
		AUGRP INT NOT NULL,
		AUNAME VARCHAR(32) NOT NULL,
		PRIMARY KEY (AUID)
);

/*role-authorities*/
create table F0321
(		RAID SERIAL NOT NULL,
		RARLID VARCHAR(32) NOT NULL,
		RAAUID VARCHAR(16) NOT NULL,
		PRIMARY KEY (RAID),
		UNIQUE (RARLID,RAAUID),
		FOREIGN KEY (RARLID) REFERENCES F0310 (RLID),
		FOREIGN KEY (RAAUID) REFERENCES F0320 (AUID)
);

/*pronounce*/
create table F1011
(		PNID SERIAL NOT NULL,
		PNLSID VARCHAR(16) NOT NULL,
		PNCT VARCHAR(1),/*utf8mb4*/
		PNPI VARCHAR(16) NOT NULL,
		PNTN SMALLINT NOT NULL,
		PNCO VARCHAR(8) NOT NULL,
		PNVO VARCHAR(8) NOT NULL,
		PNCL VARCHAR(4) NOT NULL,
		PNRM VARCHAR(4) NOT NULL,
		PRIMARY KEY (PNID),
		UNIQUE (PNLSID,PNCT,PNPI,PNTN),
		FOREIGN KEY (PNLSID) REFERENCES F1010 (LSID)
);


/*language parameters*/
create table F9410
(		LPLSID VARCHAR(16) NOT NULL,
		LPSGNG INT NOT NULL,
		LPSGCH INT NOT NULL,
		LPSGLF DECIMAL(3,1) NOT NULL,
		LPSGCW DECIMAL(3,1) NOT NULL,
		LPSGBW DECIMAL(3,1) NOT NULL,
		LPSGNB INT NOT NULL,
		LPSGFT VARCHAR(32) NOT NULL,
		LPSGFC VARCHAR(32) NOT NULL,
		LPPONG INT NOT NULL,
		LPPOCH INT NOT NULL,
		LPPOLF DECIMAL(3,1) NOT NULL,
		LPPOFT VARCHAR(32) NOT NULL,
		LPPOFC VARCHAR(32) NOT NULL,
		PRIMARY KEY (LPLSID),
		FOREIGN KEY (LPLSID) REFERENCES F1010 (LSID)
);

/*chunk*/
/*
create table F1020
(		CPID SERIAL NOT NULL,
		CPLSID VARCHAR(16) NOT NULL,
		CPSI VARCHAR(16) NOT NULL,
		CPTG VARCHAR(16) NOT NULL,
		CPFT VARCHAR(16) NOT NULL,
		CPSORT INT NOT NULL,
		PRIMARY KEY (CPID),
		UNIQUE (CPLSID,CPSI),
		FOREIGN KEY (CPLSID) REFERENCES F1010 (LSID)
);*/

/*chunk criteria*/
/*
create table F1021
(		CCID SERIAL NOT NULL,
		CCCPID INT NOT NULL,
		CCSI INT NOT NULL,
		CCTK VARCHAR(16) NOT NULL,
		CCTG VARCHAR(16) NOT NULL,
		PRIMARY KEY (CCID),
		UNIQUE (CCCPID,CCSI),
		FOREIGN KEY (CCCPID) REFERENCES F1020 (CPID)
);*/

/*categories*/
create table F1030
(		CGID SERIAL NOT NULL,
		CGLSID VARCHAR(16) NOT NULL,
		CGSI INT NOT NULL,
		CGPSI INT NOT NULL,
		CGNAME VARCHAR(1024) NOT NULL,/*utf8mb4*/
		PRIMARY KEY (CGID),
		UNIQUE (CGLSID,CGSI),
		FOREIGN KEY (CGLSID) REFERENCES F1010 (LSID)
);

/*words*/
create table F1040
(		WOID SERIAL NOT NULL,
		WOLSID VARCHAR(16) NOT NULL,
		WOCT VARCHAR(8) NOT NULL,/*utf8mb4*/
		WOPT VARCHAR(64) NOT NULL,
		WOCL VARCHAR(1) NOT NULL,
		WOSORT SMALLINT NOT NULL,
		WOST SMALLINT NOT NULL,
		PRIMARY KEY (WOID),
		UNIQUE (WOLSID,WOCT,WOPT),
		FOREIGN KEY (WOLSID) REFERENCES F1010 (LSID)
);

/*word - workflows*/
create table F1041
(		WAID SERIAL NOT NULL,
		WAWOID INT NOT NULL,
		WASI INT NOT NULL,
		WAPT VARCHAR(64) NOT NULL,
		WAST SMALLINT NOT NULL,
		WAUSID VARCHAR(32) NOT NULL,
		WACRDD VARCHAR(10) NOT NULL,
		WACRDT VARCHAR(8) NOT NULL,
		WAUPDD VARCHAR(10) NOT NULL,
		WAUPDT VARCHAR(8) NOT NULL,
		PRIMARY KEY (WAID),
		UNIQUE (WAWOID,WASI),
		FOREIGN KEY (WAWOID) REFERENCES F1040 (WOID),
		FOREIGN KEY (WAUSID) REFERENCES F0301 (USID)
);

/*word - workflow - votings */
create table F1042
(		WVID SERIAL NOT NULL,
		WVWAID INT NOT NULL,
		WVSI INT NOT NULL,
		WVUSID VARCHAR(32) NOT NULL,
		WVPO SMALLINT NOT NULL,
		WVUPDD VARCHAR(10) NOT NULL,
		WVUPDT VARCHAR(8) NOT NULL,
		PRIMARY KEY (WVID),
		UNIQUE (WVWAID,WVSI),
		UNIQUE (WVWAID,WVUSID),
		FOREIGN KEY (WVWAID) REFERENCES F1041 (WAID),
		FOREIGN KEY (WVUSID) REFERENCES F0301 (USID)
);


/*articles*/
create table F1110
(		/*field*/
		ATID SERIAL NOT NULL,
		ATCGID INT NOT NULL,
		ATSI INT NOT NULL,
		ATNAME VARCHAR(1024) NOT NULL,/*utf8mb4*/
		ATUSID VARCHAR(32) NOT NULL,
		ATUPDD VARCHAR(10) NOT NULL,
		ATUPDT VARCHAR(8) NOT NULL,
		/*constraint*/
		PRIMARY KEY (ATID),
		UNIQUE (ATCGID,ATSI),
		FOREIGN KEY (ATCGID) REFERENCES F1030 (CGID),
		FOREIGN KEY (ATUSID) REFERENCES F0301 (USID)
);


/*sentences*/
create table F1120
(		ASID SERIAL NOT NULL,
		ASATID INT NOT NULL,
		ASSI INT NOT NULL,
		ASCONT VARCHAR(128) NOT NULL,/*utf8mb4*/
		ASST SMALLINT NOT NULL,
		ASUSID VARCHAR(32) NOT NULL,
		ASUPDD VARCHAR(10) NOT NULL,
		ASUPDT VARCHAR(8) NOT NULL,
		/*constraint*/
		PRIMARY KEY (ASID),
		UNIQUE (ASATID,ASSI),
		FOREIGN KEY (ASATID) REFERENCES F1110 (ATID),
		FOREIGN KEY (ASUSID) REFERENCES F0301 (USID)
);


/*segment*/
create table F1130
(		TRASID INT NOT NULL,
		TRPI VARCHAR(1024) NOT NULL,
		TRHZ VARCHAR(128) NOT NULL,/*utf8mb4*/
		TRST SMALLINT NOT NULL,
		TRUSID VARCHAR(32) NOT NULL,
		TRUPDD VARCHAR(10) NOT NULL,
		TRUPDT VARCHAR(9) NOT NULL,
		PRIMARY KEY (TRASID),
		FOREIGN KEY (TRASID) REFERENCES F1120 (ASID),
		FOREIGN KEY (TRUSID) REFERENCES F0301 (USID)
);

/*segment - workflows*/
create table F1131
(		TAID SERIAL NOT NULL,
		TAASID INT NOT NULL,
		TASI INT NOT NULL,
		TAPI VARCHAR(1024) NOT NULL,
		TAHZ VARCHAR(128) NOT NULL,/*utf8mb4*/
		TAST SMALLINT NOT NULL,
		TAUSID VARCHAR(32) NOT NULL,
		TACRDD VARCHAR(10) NOT NULL,
		TACRDT VARCHAR(8) NOT NULL,
		TAUPDD VARCHAR(10) NOT NULL,
		TAUPDT VARCHAR(8) NOT NULL,
		PRIMARY KEY (TAID),
		UNIQUE (TAASID,TASI),
		FOREIGN KEY (TAASID) REFERENCES F1120 (ASID),
		FOREIGN KEY (TAUSID) REFERENCES F0301 (USID)
);

/*segment - workflow - votings */
create table F1132
(		TVID SERIAL NOT NULL,
		TVTAID INT NOT NULL,
		TVSI INT NOT NULL,
		TVUSID VARCHAR(32) NOT NULL,
		TVPO SMALLINT NOT NULL,
		TVUPDD VARCHAR(10) NOT NULL,
		TVUPDT VARCHAR(8) NOT NULL,
		PRIMARY KEY (TVID),
		UNIQUE (TVTAID,TVSI),
		UNIQUE (TVTAID,TVUSID),
		FOREIGN KEY (TVTAID) REFERENCES F1131 (TAID),
		FOREIGN KEY (TVUSID) REFERENCES F0301 (USID)
);

/*tagging*/
create table F1140
(		TGASID INT NOT NULL,
		TGCONT VARCHAR(128) NOT NULL,/*utf8mb4*/
		TGST SMALLINT NOT NULL,
		TGUSID VARCHAR(32) NOT NULL,
		TGUPDD VARCHAR(10) NOT NULL,
		TGUPDT VARCHAR(9) NOT NULL,
		PRIMARY KEY (TGASID),
		FOREIGN KEY (TGASID) REFERENCES F1120 (ASID),
		FOREIGN KEY (TGUSID) REFERENCES F0301 (USID)
);
